//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Idioma {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Servicios.Idioma.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string adminToolStripMenuItem {
            get {
                return ResourceManager.GetString("adminToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        public static string ayudaToolStripMenuItem {
            get {
                return ResourceManager.GetString("ayudaToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitacora.
        /// </summary>
        public static string bitacoraToolStripMenuItem {
            get {
                return ResourceManager.GetString("bitacoraToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar &gt;&gt;.
        /// </summary>
        public static string btnAddPatente {
            get {
                return ResourceManager.GetString("btnAddPatente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar &gt;&gt;.
        /// </summary>
        public static string btnAgregarFamilia {
            get {
                return ResourceManager.GetString("btnAgregarFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar &gt;&gt;.
        /// </summary>
        public static string btnAgregarPatente {
            get {
                return ResourceManager.GetString("btnAgregarPatente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar.
        /// </summary>
        public static string btnAplicarIdioma {
            get {
                return ResourceManager.GetString("btnAplicarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Pago.
        /// </summary>
        public static string btnAsignarCliente {
            get {
                return ResourceManager.GetString("btnAsignarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Clave.
        /// </summary>
        public static string btnCambiar {
            get {
                return ResourceManager.GetString("btnCambiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar.
        /// </summary>
        public static string btnConfigurar {
            get {
                return ResourceManager.GetString("btnConfigurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloquear.
        /// </summary>
        public static string btnDesbloquear {
            get {
                return ResourceManager.GetString("btnDesbloquear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despachar.
        /// </summary>
        public static string btnDespachar {
            get {
                return ResourceManager.GetString("btnDespachar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        public static string btnEnterABM {
            get {
                return ResourceManager.GetString("btnEnterABM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string btnEnterABM2 {
            get {
                return ResourceManager.GetString("btnEnterABM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturar.
        /// </summary>
        public static string btnFacturar {
            get {
                return ResourceManager.GetString("btnFacturar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar cambios.
        /// </summary>
        public static string btnGuardarFamilia {
            get {
                return ResourceManager.GetString("btnGuardarFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar familia.
        /// </summary>
        public static string btnGuardarFamilia2 {
            get {
                return ResourceManager.GetString("btnGuardarFamilia2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string btnGuardarNuevaF {
            get {
                return ResourceManager.GetString("btnGuardarNuevaF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string btnRegistrarCliente {
            get {
                return ResourceManager.GetString("btnRegistrarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Selección.
        /// </summary>
        public static string btnRemoverCarrito {
            get {
                return ResourceManager.GetString("btnRemoverCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string btnSelect {
            get {
                return ResourceManager.GetString("btnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string btnSelectVentas {
            get {
                return ResourceManager.GetString("btnSelectVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar sin sesión.
        /// </summary>
        public static string btnSinSesion {
            get {
                return ResourceManager.GetString("btnSinSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaciar.
        /// </summary>
        public static string btnVaciar {
            get {
                return ResourceManager.GetString("btnVaciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta.
        /// </summary>
        public static string btnVenta {
            get {
                return ResourceManager.GetString("btnVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar.
        /// </summary>
        public static string btnVerif {
            get {
                return ResourceManager.GetString("btnVerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string clientesToolStripMenuItem {
            get {
                return ResourceManager.GetString("clientesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compras.
        /// </summary>
        public static string comprasToolStripMenuItem {
            get {
                return ResourceManager.GetString("comprasToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string Español {
            get {
                return ResourceManager.GetString("Español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Clave.
        /// </summary>
        public static string gbCambiarClave {
            get {
                return ResourceManager.GetString("gbCambiarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Datos Pago.
        /// </summary>
        public static string gbDatosPago {
            get {
                return ResourceManager.GetString("gbDatosPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloquear Usuarios.
        /// </summary>
        public static string gbDesbloquearUsuarios {
            get {
                return ResourceManager.GetString("gbDesbloquearUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familias.
        /// </summary>
        public static string gbFamilias {
            get {
                return ResourceManager.GetString("gbFamilias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador Facturas.
        /// </summary>
        public static string gbIdFacturas {
            get {
                return ResourceManager.GetString("gbIdFacturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva.
        /// </summary>
        public static string gbNuevaFamilia {
            get {
                return ResourceManager.GetString("gbNuevaFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patentes.
        /// </summary>
        public static string gbPatentes {
            get {
                return ResourceManager.GetString("gbPatentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Cliente.
        /// </summary>
        public static string gbRegistroCliente {
            get {
                return ResourceManager.GetString("gbRegistroCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeleccionadorFacturas.
        /// </summary>
        public static string gbSeleccionFactura {
            get {
                return ResourceManager.GetString("gbSeleccionFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventas no facturadas.
        /// </summary>
        public static string gbVentasNoF {
            get {
                return ResourceManager.GetString("gbVentasNoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string grpbxCMUsu {
            get {
                return ResourceManager.GetString("grpbxCMUsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrito.
        /// </summary>
        public static string grpCarrito {
            get {
                return ResourceManager.GetString("grpCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string grpPatentes {
            get {
                return ResourceManager.GetString("grpPatentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existencias.
        /// </summary>
        public static string grpStockVentas {
            get {
                return ResourceManager.GetString("grpStockVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas.
        /// </summary>
        public static string idiomasToolStripMenuItem {
            get {
                return ResourceManager.GetString("idiomasToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string Inglés {
            get {
                return ResourceManager.GetString("Inglés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Usuario:.
        /// </summary>
        public static string lblABMNUsu {
            get {
                return ResourceManager.GetString("lblABMNUsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña:.
        /// </summary>
        public static string lblABMPUsu {
            get {
                return ResourceManager.GetString("lblABMPUsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Familias.
        /// </summary>
        public static string lblAddFamilia {
            get {
                return ResourceManager.GetString("lblAddFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar patentes.
        /// </summary>
        public static string lblAddPatente {
            get {
                return ResourceManager.GetString("lblAddPatente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string lblApellidoCliente {
            get {
                return ResourceManager.GetString("lblApellidoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar DNI de cliente a carrito:.
        /// </summary>
        public static string lblAsignarCliente {
            get {
                return ResourceManager.GetString("lblAsignarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad:.
        /// </summary>
        public static string lblCantidadVentas {
            get {
                return ResourceManager.GetString("lblCantidadVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los usuarios.
        /// </summary>
        public static string lblCbUsuarios {
            get {
                return ResourceManager.GetString("lblCbUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave actual:.
        /// </summary>
        public static string lblClaveActual {
            get {
                return ResourceManager.GetString("lblClaveActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave nueva:.
        /// </summary>
        public static string lblClaveNueva {
            get {
                return ResourceManager.GetString("lblClaveNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuotas.
        /// </summary>
        public static string lblCuotas {
            get {
                return ResourceManager.GetString("lblCuotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI Cliente.
        /// </summary>
        public static string lblDniFactura {
            get {
                return ResourceManager.GetString("lblDniFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicilio.
        /// </summary>
        public static string lblDomicilioCliente {
            get {
                return ResourceManager.GetString("lblDomicilioCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas las familias.
        /// </summary>
        public static string lblFamilias {
            get {
                return ResourceManager.GetString("lblFamilias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI.
        /// </summary>
        public static string lblIdCliente {
            get {
                return ResourceManager.GetString("lblIdCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Factura.
        /// </summary>
        public static string lblIdFactura {
            get {
                return ResourceManager.GetString("lblIdFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string lblLang {
            get {
                return ResourceManager.GetString("lblLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes Y Año expiración.
        /// </summary>
        public static string lblMesYAñoVenc {
            get {
                return ResourceManager.GetString("lblMesYAñoVenc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string lblNombreCliente {
            get {
                return ResourceManager.GetString("lblNombreCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Tarjeta.
        /// </summary>
        public static string lblNumTarjeta {
            get {
                return ResourceManager.GetString("lblNumTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string lblPass {
            get {
                return ResourceManager.GetString("lblPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cada cuota: .
        /// </summary>
        public static string lblSubtotalCuotas {
            get {
                return ResourceManager.GetString("lblSubtotalCuotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal: .
        /// </summary>
        public static string lblSubtotalVenta {
            get {
                return ResourceManager.GetString("lblSubtotalVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string lblTelefonoCliente {
            get {
                return ResourceManager.GetString("lblTelefonoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string lblTipoTarjeta {
            get {
                return ResourceManager.GetString("lblTipoTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas las patentes.
        /// </summary>
        public static string lblTodasPatentes {
            get {
                return ResourceManager.GetString("lblTodasPatentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Usuario.
        /// </summary>
        public static string lblUsu {
            get {
                return ResourceManager.GetString("lblUsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maestros.
        /// </summary>
        public static string maestrosToolStripMenuItem {
            get {
                return ResourceManager.GetString("maestrosToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfiles.
        /// </summary>
        public static string perfilesToolStripMenuItem {
            get {
                return ResourceManager.GetString("perfilesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string productosToolStripMenuItem {
            get {
                return ResourceManager.GetString("productosToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        public static string proveedoresToolStripMenuItem {
            get {
                return ResourceManager.GetString("proveedoresToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes.
        /// </summary>
        public static string reportesToolStripMenuItem {
            get {
                return ResourceManager.GetString("reportesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string salirToolStripMenuItem {
            get {
                return ResourceManager.GetString("salirToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despachar.
        /// </summary>
        public static string tmiDespachar {
            get {
                return ResourceManager.GetString("tmiDespachar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturar.
        /// </summary>
        public static string tmiFacturar {
            get {
                return ResourceManager.GetString("tmiFacturar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccion y Carrito.
        /// </summary>
        public static string tmiSeleccionYCarrito {
            get {
                return ResourceManager.GetString("tmiSeleccionYCarrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        public static string tsmiArchivo {
            get {
                return ResourceManager.GetString("tsmiArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string usuariosToolStripMenuItem {
            get {
                return ResourceManager.GetString("usuariosToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string usuarioToolStripMenuItem {
            get {
                return ResourceManager.GetString("usuarioToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventas.
        /// </summary>
        public static string ventasToolStripMenuItem {
            get {
                return ResourceManager.GetString("ventasToolStripMenuItem", resourceCulture);
            }
        }
    }
}
